Document: gnunet
Title: Debian gnunet Manual
Author: <insert document author here>
Abstract: This manual describes what gnunet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnunet/gnunet.sgml.gz

Format: postscript
Files: /usr/share/doc/gnunet/gnunet.ps.gz

Format: text
Files: /usr/share/doc/gnunet/gnunet.text.gz

Format: HTML
Index: /usr/share/doc/gnunet/html/index.html
Files: /usr/share/doc/gnunet/html/*.html
